### ISSUE TITLE
makeDraggable not present in mxUtils

### ISSUE THREAD

**Issue by julienmarantes** [asual/mxgraph-factory#2]
Trying to make some drag feature but `makeDraggable` which I need don't seem to be present in the typing ? 
 
[Documentation link](https://jgraph.github.io/mxgraph/docs/js-api/files/util/mxUtils-js.html#mxUtils.makeDraggable)

**Comment by asual** [comment]
The mxgraph typings are borrowed from https://github.com/lgleim/mxgraph-typings and it will be great if any missing pieces are applied there first.

The particular `mxDraggable` method belongs to `mxUtils` which is of type `any`. You should be able to use it but it won't give you any type safety.

**Comment by julienmarantes** [comment]
I see, this part is really time consuming.

Thanks for the info, for me this issue is closed. Or maybe let it open for hypothetical future updates

EDIT : 

Maybe not related but some classes like for example `mxGraphHandler` require to use `prototype`  to access attributes and methods like so (this is from an official example): 

`mxGraphHandler.prototype.guidesEnabled = true;`

Attributes are not provided how can I access them ?

EDIT 2 : 

ok I'm not too familiar with the typing javascript -> typescript. It seems the attributes juste need to be added to the `mxgraph-typing.d.ts`
