### ISSUE TITLE
Contact: let's share efforts to implement 'mxgraph-type-definitions'

### ISSUE THREAD

**Issue by tbouffard** [asual/mxgraph-factory#9]
Hi @asual
We have recently started a [dedicated community initiative](https://github.com/process-analytics/mxgraph-road-to-DefinitelyTyped) to provide mxGraph type definitions through the [DefinitelyTyped project](https://definitelytyped.org/).

Would you agree to join?
I know that in your repository, you have integrated type definitions initially taken from https://github.com/lgleim/mxgraph-typings and you updating regularly.
I am currently using a [repository derived from yours](https://github.com/process-analytics/ts-mxgraph) and I also need to do the same updates as you do. So there may be an opportunity to join forces on this subject.

**Comment by asual** [comment]
Hey Thomas,

I no longer work on a project that requires mxGraph and I probably won't have the time to contribute actively. Feel free to use any of the type definitions in this repo and move them to the DefinitelyTyped project. It's the standard for such type definitions.

The main goal of this project was to provide the required Webpack configuration that turns mxGraph into a CommonJS compatible package. The type definitions were added just for convenience and can be easily dropped if there is a better alternative.

Good luck!

**Comment by tbouffard** [comment]
thanks for your answer and for your encouraging words :smile:
